# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kennykao.me
title:
email: kennykao1203@gmail.com
author: Kenny Kao
description: > # "Kenny Kao's Resume 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 Kenny Kao. All Rights Reserved.'
credits: 'Credits: Template: Landing Page. Github Pages'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/kennykao/
